import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  homeContainer: {
    flex: 1,
    paddingHorizontal: 11,
    paddingTop: 50,
  },
  homeHeaderView: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  headerText: {
    fontWeight: "bold",
    fontSize: 42,
    marginRight: 21,
    marginLeft: 11,
  },
  inputStyle: {
    height: 42,
    width: 300,
    borderRadius: 8,
    borderColor: "#c0c0c0",
    borderWidth: 1,
    paddingLeft: 16,
  },
  showResText: {
    fontStyle: "italic",
    margin: 11,
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  innerScrollView: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    flexWrap: "wrap",
  },
  whiteCard: {
    height: 320,
    width: 320,
    borderRadius: 8,
    margin: 11,
    backgroundColor: "#FFF",
    shadowColor: 'lightblue',
    shadowOffset: { width: 1, height: 3 },
    shadowRadius: 3,
    shadowOpacity: 1,
    elevation: 3,
  },
  profileImg: {
    height: 150,
    width: 150,
    borderRadius: 75,
    margin: 32,
    alignSelf: "center",
  },
  profileName: {
    textAlign: "center",
    alignSelf: "center",
    marginBottom: 11,
    fontWeight: "bold",
  },
  scoreText: {
    textAlign: "center",
    alignSelf: "center",
  },
  gitLink: {
    color: "blue",
    fontSize: 18,
    textAlign: "center",
    alignSelf: "center",
    marginVertical: 11,
    textDecorationLine: 'underline',
  },
  alignment: {
    width: 320,
    borderRadius: 8,
    marginHorizontal: 11,
  },
  pagLoaderView: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 5,
  },
  pagButtonView: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
  },
  pagButton: {
    alignSelf: "center",
    height: 45,
    width: 300,
    borderRadius: 8,
    backgroundColor: "#000",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  pagButtonText: {
    color: "#FFF",
    fontWeight: "bold",
    fontSize: 18,
  },
});
